function [VarName1,Area,Mean,StdDev,Mode,Min,Max,X,Y,XM,YM,Perim,BX,BY,Width,Height,Major,Minor,Angle,Circ,Feret,IntDen,Median,Skew,Kurt,Area1,RawIntDen,Slice,FeretX,FeretY,FeretAngle,MinFeret,AR,Round,Solidity] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,AREA,MEAN,STDDEV,MODE,MIN,MAX,X,Y,XM,YM,PERIM,BX,BY,WIDTH,HEIGHT,MAJOR,MINOR,ANGLE,CIRC,FERET,INTDEN,MEDIAN,SKEW,KURT,AREA1,RAWINTDEN,SLICE,FERETX,FERETY,FERETANGLE,MINFERET,AR,ROUND,SOLIDITY]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VARNAME1,AREA,MEAN,STDDEV,MODE,MIN,MAX,X,Y,XM,YM,PERIM,BX,BY,WIDTH,HEIGHT,MAJOR,MINOR,ANGLE,CIRC,FERET,INTDEN,MEDIAN,SKEW,KURT,AREA1,RAWINTDEN,SLICE,FERETX,FERETY,FERETANGLE,MINFERET,AR,ROUND,SOLIDITY]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,Area,Mean,StdDev,Mode,Min,Max,X,Y,XM,YM,Perim,BX,BY,Width,Height,Major,Minor,Angle,Circ,Feret,IntDen,Median,Skew,Kurt,Area1,RawIntDen,Slice,FeretX,FeretY,FeretAngle,MinFeret,AR,Round,Solidity] = importfile('TN347_1_roi_stats.csv',2, 100);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/10/11 12:33:39

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
Area = dataArray{:, 2};
Mean = dataArray{:, 3};
StdDev = dataArray{:, 4};
Mode = dataArray{:, 5};
Min = dataArray{:, 6};
Max = dataArray{:, 7};
X = dataArray{:, 8};
Y = dataArray{:, 9};
XM = dataArray{:, 10};
YM = dataArray{:, 11};
Perim = dataArray{:, 12};
BX = dataArray{:, 13};
BY = dataArray{:, 14};
Width = dataArray{:, 15};
Height = dataArray{:, 16};
Major = dataArray{:, 17};
Minor = dataArray{:, 18};
Angle = dataArray{:, 19};
Circ = dataArray{:, 20};
Feret = dataArray{:, 21};
IntDen = dataArray{:, 22};
Median = dataArray{:, 23};
Skew = dataArray{:, 24};
Kurt = dataArray{:, 25};
Area1 = dataArray{:, 26};
RawIntDen = dataArray{:, 27};
Slice = dataArray{:, 28};
FeretX = dataArray{:, 29};
FeretY = dataArray{:, 30};
FeretAngle = dataArray{:, 31};
MinFeret = dataArray{:, 32};
AR = dataArray{:, 33};
Round = dataArray{:, 34};
Solidity = dataArray{:, 35};


